version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:24
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity

  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"

  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - "6379:6379"